services:
  - type: web
    name: aqar-hub-api
    runtime: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false # Render will ask you to paste your Neon connection string in the UI during deployment
